spring.application.name=health-records

spring.datasource.url=jdbc:h2:mem:health-records
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true